apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello
    app.kubernetes.io/instance: resources-demo
  name: hello
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  - port: 9080
    protocol: TCP
    targetPort: 9080
  selector:
    app: hello
