apiVersion: v1
kind: LimitRange
metadata:
  name: defaultlimits
spec:
  limits:
  - max:
      cpu: "4"
      memory: 2Gi
    default:
      cpu: "200m"
      memory: 200Mi
    min:
      cpu: "10m"
      memory: 10Mi
    type: Container
  requests:
  - max:
      cpu: "4"
      memory: 2Gi
    default:
      cpu: "200m"
      memory: 200Mi
    min:
      cpu: "10m"
      memory: 10Mi
    type: Container
