apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"payara:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"payara\")].image"}]'
  name: payara
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: payara
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: payara
    spec:
      containers:
      - image: "updated-by-is-operator"
        imagePullPolicy: IfNotPresent
        name: payara
        ports:
        - containerPort: 4848
          protocol: TCP
        - containerPort: 8009
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8181
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
