apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: payara
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deployment: payara
status:
  loadBalancer: {}
